### ISSUE TITLE
баг №1 регистрация 

### ISSUE THREAD

**Issue by KDI21** [AleksandrFeoktistov/symfony7#2]
тест №1
**задание**: регистрация
**действие**: на странице регистрации заполнить поля ввода данных
(ввести login "qweqwe", password "qwe123qwe", повторить пароль, email "dima310426@gmail.com")
**ожидаемый результат**: пройти регистрацию и попасть на главную страницу
**фактический результат** после регистрации перекидывает на залогинется

**Comment by AleksandrFeoktistov** [comment]
ok
