### ISSUE TITLE
баг №2 проект 

### ISSUE THREAD

**Issue by KDI21** [AleksandrFeoktistov/symfony7#3]
тест №2
(все делается под ником ****)
**задание:** создание проекта.
**действие**: нажать на кнопку создание проекта и дать имя проэкту , после создания изменить его и потом  удалить
**ожидаемый результат:** проект создан, изменен удолен
**фактический результат**:не могу удалить  и изменить проект который создал

**Comment by AleksandrFeoktistov** [comment]
ok

**Comment by KDI21** [comment]
** исправлено:** не могу удалить и изменить проект который создал
**действие:** редактирование 
**ожидаемый результат:** после окончания редактирования должно отправлять в просмотр проекта
**фактический  результат** производит обновление , но оставляет на тойже странице
