### ISSUE TITLE
баг №3 тикет

### ISSUE THREAD

**Issue by KDI21** [AleksandrFeoktistov/symfony7#4]
тест №3
(делается все длок ником **asdsad**)
**задание:** создание тикета.
**действие:** нажать на кнопку создание тикита (заполнить необходимые поля), проверить количество статусов,Тикет должен быть назначен (assigned) одному человеку. проверить отметился ли кто его создал прикрепить файл,
редактипование и потом удаление, также провести эти действия с тикетами которые я  не создавал 

**oожидаемый результат:** тикет создан отредактираван и удален, нет доступа к не сщзданым мною тикетам 

**фактический результат:**
могу удалить и редактировать тикет  который я не создавал
тикет создан
**НО** не могу редактировать созданные  мною тикеты

**Comment by AleksandrFeoktistov** [comment]
ok

**Comment by KDI21** [comment]
**выполнить:**
