### ISSUE TITLE
баг №4 комиты 

### ISSUE THREAD

**Issue by KDI21** [AleksandrFeoktistov/symfony7#5]
ест №5
**задание:** проверка прав доступа
**действие:** попытаться сделать то что не доступно для пользователя результат записать

**фактический результат:**
на не созданных мною комитах имеется ссылка в edit при ее нажатии выкидывает на страницу фраймворка с сообщением  **"доступ закрыт"**
не могу удалить и изменить свои созданные комиты 
сообщение   **"доступ закрыт"**

**Comment by AleksandrFeoktistov** [comment]
ok
