### ISSUE TITLE
баг №5 users 

### ISSUE THREAD

**Issue by KDI21** [AleksandrFeoktistov/symfony7#6]
**действие:** перейти в вкладку users  под ником  asdsad
и проверить возможности пользователя ,а именно:
1) редактировать учетные записи
2) удаление учетак 
3) добавить нового пользователя

**ожидаемый результат:**
как пользователь я могу узнать поподробнее о других пользователях и  немогу не как изменять их данные или удалять.  
**фактический результат:**
пользователь  может удалять учетные записи в таблице с users, 
но не может узнать поподробнее о другом пользователе и о себе тоже.

**Comment by AleksandrFeoktistov** [comment]
ok
