### ISSUE TITLE
тикет

### ISSUE THREAD

**Issue by KDI21** [AleksandrFeoktistov/symfony7#8]
тест №3
(делается все длок ником asdsad)
**задание:** создание тикета.
**действие:** нажать на кнопку создание тикита (заполнить необходимые поля), проверить количество статусов,Тикет должен быть назначен (assigned) одному человеку. проверить отметился ли кто его создал прикрепить файл,
редактирование и потом удаление, также провести эти действия с тикетами которые я не создавал

**oожидаемый** **результат:** тикет создан отредактираван и удален, нет доступа к не сщзданым мною тикетам
**фактический результат ** могу удалить проект который не создавал

**Comment by AleksandrFeoktistov** [comment]
исп
